server:
  port: 8080

spring:
  profiles:
    include: redis,druid,log,database
  config:
    location: classpath:config/*

#================mybatis===============================================================
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: 'com.example.demo.bean.po'
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新 mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.adg.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.adg.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.adg.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#=================================================================================